require: rubocop-sketchup

inherit_from:
  - https://raw.githubusercontent.com/SketchUp/rubocop-sketchup/master/sketchup-style.yml
  # - .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
  - src/*/vendor/**/*
  SketchUp:
    SourcePath: src
    TargetSketchUpVersion: 2014
    Exclude:
    - profiling/**/*
    - skippy/**/*
    - tests/**/*
  TargetRubyVersion: 2.2 # Should have been 2.0 but RuboCop dropped support.


SketchupSuggestions/Compatibility:
  Exclude:
  - src/tt_truebend/dpi.rb

# In debug code the encoding bug in Ruby isn't a big issue.
SketchupSuggestions/FileEncoding:
  Exclude:
  - src/tt_truebend/debug.rb


Layout/ClosingParenthesisIndentation:
  Enabled: false

# Root extension file got an unusual indentation. That's fine.
# This is very particular to my TT::Plugin::Extension name scheme.
# Whoever might read this; the ::Plugin:: part is legacy naming I now regret.
Layout/IndentationWidth:
  Exclude:
    - 'src/*.rb'

# Spaces are fine to line up matrices etc to be more readable.
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

# Spaces are fine to line up matrices etc to be more readable.
Layout/SpaceInsideParens:
  Enabled: false

# Need to rescue Exception for error logging.
Lint/RescueException:
  Enabled: false


# Tests should have not upper size limit.
Metrics/ClassLength:
  Exclude:
    - 'profiling/**/*'
    - 'tests/**/*'


# Tests follow a different naming convention.
Naming/ClassAndModuleCamelCase:
  Exclude:
    - 'profiling/**/*'
    - 'tests/**/*'

# Tests follow a different naming convention.
Naming/FileName:
  Exclude:
    - 'profiling/**/*'
    - 'tests/**/*'

# Tool classes must use the SketchUp API method names.
Naming/MethodName:
  Exclude:
    - '**/*_tool.rb'
    - '**/observers/*.rb'
    - '**/tools/*.rb'
    - '**/manipulators/*.rb'

# Bug: https://github.com/rubocop-hq/rubocop/issues/6761
Naming/UncommunicativeMethodParamName:
  Exclude:
    - 'src/tt_truebend/tools/truebend.rb'


Metrics/ClassLength:
  Max: 300

# Ideal length should be 80. But some times it reads better to let the line
# bleed over by a little. In this project there are enough of these cases that
# the RuboCop max is set to 100.
Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 30


Style/DoubleNegation:
  Enabled: false
