require: rubocop-sketchup

inherit_from:
  - https://raw.githubusercontent.com/SketchUp/rubocop-sketchup/5bb95f8781bd19ea7592f3c6b9c50ee18bba71a8/sketchup-style.yml
  # - .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
  - src/*/vendor/**/*
  NewCops: enable
  SketchUp:
    SourcePath: src
    TargetSketchUpVersion: 2014
    Exclude:
    - Gemfile
    - profiling/**/*
    - skippy/**/*
    - tests/**/*
  TargetRubyVersion: 2.0


SketchupSuggestions/Compatibility:
  Exclude:
  - src/tt_truebend/dpi.rb

# In debug code the encoding bug in Ruby isn't a big issue.
SketchupSuggestions/FileEncoding:
  Exclude:
  - src/tt_truebend/debug.rb


Layout/ClosingParenthesisIndentation:
  Enabled: false

# Root extension file got an unusual indentation. That's fine.
# This is very particular to my TT::Plugin::Extension name scheme.
# Whoever might read this; the ::Plugin:: part is legacy naming I now regret.
Layout/IndentationWidth:
  Exclude:
    - 'src/*.rb'

# Ideal length should be 80. But some times it reads better to let the line
# bleed over by a little. In this project there are enough of these cases that
# the RuboCop max is set to 100.
Layout/LineLength:
  Max: 100

# Spaces are fine to line up matrices etc to be more readable.
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

# Spaces are fine to line up matrices etc to be more readable.
Layout/SpaceInsideParens:
  Enabled: false


# Need to rescue Exception for error logging.
Lint/RescueException:
  Enabled: false


# Tests should have not upper size limit.
Metrics/ClassLength:
  Max: 300
  Exclude:
    - 'profiling/**/*'
    - 'tests/**/*'

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 110

Metrics/ParameterLists:
  Exclude:
    - 'src/tt_truebend/bender.rb'


# Tests follow a different naming convention.
Naming/ClassAndModuleCamelCase:
  Exclude:
    - 'profiling/**/*'
    - 'tests/**/*'

# Tests follow a different naming convention.
Naming/FileName:
  Exclude:
    - 'profiling/**/*'
    - 'tests/**/*'

# Tool classes must use the SketchUp API method names.
Naming/MethodName:
  Exclude:
    - '**/*_tool.rb'
    - '**/observers/*.rb'
    - '**/tools/*.rb'
    - '**/manipulators/*.rb'


Style/DoubleNegation:
  Enabled: false

# Need to perform testing before enabling frozen string literals.
Style/FrozenStringLiteralComment:
  Enabled: false

Style/AccessorGrouping:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/MultilineTernaryOperator:
  Exclude:
  - 'src/tt_truebend/geom/polar_projection.rb'

# Some times parentheses reads clearer.
Style/TernaryParentheses:
  Enabled: false
